# Generated by Django 5.1.3 on 2024-11-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_tag_room_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='tags',
        ),
        migrations.AddField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(blank=True, to='rooms.tag'),
        ),
    ]
