# Generated by Django 5.1 on 2024-12-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_room_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(blank=True, to='rooms.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
