services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend

  backend:
    build:
      context: ./backend/base
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    container_name: backend
    volumes:
      - ./backend/base:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    entrypoint: ["/app/entrypoint.sh"]

  frontend:
    build:
      context: ./frontend/webchat
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"